version: "3"

services:
  web:
    build:
      context: .

      dockerfile: ./Dockerfile
    command: ["./startup.sh"]

    ports:
      - 8000:8000
    volumes:
      - ./src/:/src
      - pip_cache:/usr/local/lib/python3/site-packages
    depends_on:
      - db
    env_file:
      - ./.envs/.postgres

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envs/.postgres

volumes:
  postgres_data:
  pip_cache: