name: CI
on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
       - name: Lint with flake8
         run: |
            pip install flake8
            flake8 --extend-ignore=E302,E101,E131,W191,W293,W292 --count --select=E9,F63,F7,F82 --exclude=*.pyc,*migrations* --show-source --statistics 
            flake8 --extend-ignore=E302,E101,E131,W191,W293,W292 --count --max-complexity=10 --max-line-length=226 --exclude=*.pyc,*migrations* --statistics
          
       - name: Create test environment
         run: docker-compose up --build
       - name: Run coverage tests
         run: docker exec web bash -c "coverage run manage.py test && coverage report -m"
